---
title: "lab2"
author: "Felix Seo"
date: "2023-10-01"
output: html_document
---

```{r}
library(tidyverse)
library(rstan)
```

```{r}
# part 1 a
data_aspirin <- read_delim("../data/aspirin.txt")

data_aspirin %>% 
  mutate(reduction = Before - After) %>% 
  ggplot(aes(x = Before, y = reduction)) +
  geom_point()
```

```{r}
#part 1 b
x_mean <- data_aspirin$Before %>% mean()

fit_1_b <- data_aspirin %>% 
  mutate(x = Before - x_mean) %>%
  mutate(y = Before - After) %>%
  {list("N" = 12, "y" = .$y, "x" = .$x)} %>% 
  {stan("model_1_b.stan", 
  data = .,
  chains = 4,             # number of Markov chains
  warmup = 1000,          # number of warmup iterations per chain
  iter = 3000,            # total number of iterations per chain
  cores = 2,              # number of cores (could use one per chain)
  refresh = 0,            # no progress shown
  seed = 990108
  )}


cred_int_95 <- fit_1_b %>% 
  summary(pars = "beta", probs = c(0.025, 0.975)) %>% 
  {.$summary[4:5]}

fit_1_b %>% 
  rstan::extract(pars = "beta") %>% 
  unlist(use.names = FALSE) %>% 
  as.data.frame() %>% 
  rename("beta" = ".") %>% 
  ggplot() +
  geom_histogram(
    aes(x = beta, y = after_stat(density)),
    bins = 100, 
    color = "black", 
    fill = "white"
  ) +
  geom_vline(
    data = NULL,
    xintercept = cred_int_95[1],
    linetype = "dashed", 
    size = 0.5,
    color = "red"
  ) +
  geom_vline(
    data = NULL,
    xintercept = cred_int_95[2],
    linetype = "dashed", 
    size = 0.5,
    color = "red"
  )


```

```{r}
# part 1 c

fit_1_c <- data_aspirin %>% 
  mutate(x = Before - x_mean, y = Before - After) %>%
  {list("N" = 12, "y" = .$y, "x" = .$x, "N_new" = 1, "x_new" = c(100 - x_mean))} %>% 
  {stan("model_1_c.stan", 
  data = .,
  chains = 4,             # number of Markov chains
  warmup = 200,          # number of warmup iterations per chain
  iter = 1000,            # total number of iterations per chain
  cores = 2,              # number of cores (could use one per chain)
  refresh = 0,            # no progress shown
  seed = 990108
  )}

fit_1_c

```

